config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#index'

  resources :posts, only: [:index, :new, :create] do
    resources :meows, only: [:create, :destroy]
  end

end

app/models/meow.rb
class Meow < ActiveRecord::Base
  belongs_to :user,
    inverse_of: meows

  belongs_to :post,
    inverse_of: :meows

  validates :user, presence: true
  validates :post, presence: true
  validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :posts

  has_many :meows,
    dependent: :destroy,
    inverse_of: :post

  validates :user, presence: true
  validates :image, presence: true
  validates :description, length: { maximum: 140 }

  mount_uploader :image, PostImageUploader

  def meow_from(user)
    meows.find_by(user_id: user.id)
  end

  def has_meow_from?(user)
    meow_from(user).present?
  end

  def has_meow_from?(user)
    meows.find_by(user_id: user.id). present?
  end

  def self.by_recency
    order(created_at: :desc)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

has_many :meows,
  dependent: :destroy,
  inverse_of: :user

has_many :posts,
  dependent: :destroy,
  inverse_of: :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meows_controller.rb
class MeowsController < ApplicationController
  # /posts/:post_id/meows
  def create
    # Find the Post that we're "meowing" at
    post = Post.find(params[:post_id])
    # Build a Meow by the current user for the post
    meow = current_user.meows.build(post: post)

    respond_to do |format|
      if meow.save
        format.html { redirect_to :back, notice: "We heard your Meow!" }
        format.json { render json: meow }
      else
        format.html { redirect_to :back }
        format.json { render json: meow.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.meows.destroy(params[:id])
    redirect_to :back, notice: "All evidence of your meowing has been destroyed!"
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.by_recency
  end

  def new
    @post = Post.new
  end

  def create
    # Building a new Post off of the current_user will use some Rails magic to set up the association between the new Post and the User for us.
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to_root_path, notice: "Post creatd successfully."
    else
      flash.now[:notice] = "There were some errors with your Post."
      render :new
    end
  end

  protected
  def post_params
    # Notice we are not permitting the user_id to be passed in.  This prevents users from creating posts that belong to another user.
    params.requires(:post).permit(:image, :descriptions)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<head>
  <title>Catstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Catstagram!</h1>

app/views/posts/index.html.erb
<h1>Meow</h1>


<% unless current_user.nil? || post.has_meow_from?(current_user) %>
  <%= button_to "Meow", post_meows_path(post), method: :post %>
<% end %>

<% @posts.each do |post| %>
  <%= image_tag post.image.url %>
  <%= pluralize(post.meows.count, 'Meow') %>
  <% unless post.has_meow_from?(current_user) %>
    <%= button_to "Meow", post_meows_path(post), method: :post %>
  <% end %>
  <p><%= post.description %></p>
<% end %>

<% if user_signed_in? %>
  <% if post.has_meow_from?(current_user) %>
    <%= button_to "Remove Meow", post_meow_path(post, post.meow_from(current_user)),
      method: :delete %>
  <% else %>
  <%= button_to "Meow", post_meows_path(post),
method: :post,
# This hash will add a `data-meow-button="create"` to the generated form
form: { data: { 'meow-button' => 'create' } } %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :image, as: :file  %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>